"""Shared utilities for SMP02 test scripts."""

import time

import pyvisa

SMP_ADDRESS = "GPIB1::28::INSTR"
SMP_IDN_HINT = "SMP02"

READS_PER_POINT = 3
READ_DELAY = 0.05
POINT_DELAY = 0.15


def connect_smp(verbose=True, address=SMP_ADDRESS, hint=SMP_IDN_HINT):
    """Open a pyvisa session to the SMP02 and return the device handle.

    Retries the *IDN? query up to 10 times to allow the instrument to
    finish its boot sequence. Raises ConnectionError if the identity
    never matches ``hint``.
    """
    rm = pyvisa.ResourceManager()
    if verbose:
        print(f"Connecting to {address}...", end="", flush=True)
    dev = rm.open_resource(address)
    dev.timeout = 5000
    idn = None
    for _ in range(10):
        try:
            idn = dev.query("*IDN?")
        except Exception:
            idn = None
        if idn and hint in idn:
            if verbose:
                print(f"connected to {idn.strip()}")
            return dev
        time.sleep(0.1)
    try:
        dev.close()
    except Exception:
        pass
    raise ConnectionError(f"Unexpected identity response {idn!r} from {address}")


def read_tp(dev, tp):
    """Read a diagnostic test point, return averaged value."""
    time.sleep(POINT_DELAY)
    values = []
    for i in range(READS_PER_POINT):
        if i > 0:
            time.sleep(READ_DELAY)
        reply = dev.query(f":DIAG:MEAS:POINT{tp}?")
        values.append(float(reply))
    return sum(values) / len(values)


def query_options(dev):
    """Query *OPT? and return set of installed option names."""
    reply = dev.query("*OPT?").strip()
    return {o for o in reply.split(",") if o != "0"}


def query_hw_modules(dev):
    """Query :DIAG:INFO:MOD? and return dict of module info."""
    reply = dev.query(":DIAG:INFO:MOD?").strip()
    modules = {}
    for entry in reply.split(","):
        parts = entry.strip().split()
        if len(parts) >= 3:
            name = parts[0]
            var = parts[1]
            rev = parts[2]
            modules[name] = (var, rev)
    return modules


def list_hw_modules(dev):
    """Print hardware modules from :DIAG:INFO:MOD?."""
    hw = query_hw_modules(dev)
    for name, (var, rev) in hw.items():
        print(f"  {name:8s}  {var}  {rev}")


def drain_err_queue(dev, max_drain=64):
    """Drain :SYST:ERR? queue, return list of non-"No error" entries."""
    errors = []
    for _ in range(max_drain):
        reply = dev.query(":SYST:ERR?").strip()
        if not reply:
            break
        code = reply.split(",", 1)[0].strip()
        if code in ("0", "+0"):
            break
        errors.append(reply)
    return errors


def query_scalar(dev, cmd, default=""):
    """Query a scalar SCPI value, returning stripped reply or default on error."""
    try:
        return dev.query(cmd).strip()
    except Exception as exc:
        return f"{default} (query failed: {exc})"


# UTILITIES/PROTECT lock levels (band-1 §6.4.1.1, user-manual p.206).
# Passwords are fixed in firmware. Empirically on SMP02 FW 3.70 the
# password is NOT validated over GPIB (any parameter flips STATe to 0)
# and the flag does not gate SCPI access; it only hides front-panel
# menu items. Kept here so unlock_protect() still issues the correct
# pair if/when a firmware actually enforces it.
UNLOCK_PASSWORDS = {
    1: "123456",  # PULSE GEN, YFOM, ALC AMP, LEVEL view menus
    2: "520805",  # REF OSC menu
    3: "490727",  # UTILITIES/DIAG/PARAM menu
}


def unlock_protect(dev, level=1):
    """Clear the UTILITIES/PROTECT lock flag for LEVEL n.

    Sends :SYST:PROT<n>:STAT OFF, <password>. Returns the list of
    error-queue entries generated by the command (empty list = success).
    The manual (p.206) states that a wrong password yields -224
    "Illegal parameter value", but FW 3.70 does not actually enforce
    this — see module docstring note above.
    """
    if level not in UNLOCK_PASSWORDS:
        raise ValueError(f"unsupported lock level {level}")
    drain_err_queue(dev)
    dev.write(f":SYST:PROT{level}:STAT OFF, {UNLOCK_PASSWORDS[level]}")
    return drain_err_queue(dev)


# A9 ALC Amplifier exists in two non-interchangeable board variants.
# Source: service manual band-2, Register 4 (1035.6301.02) / Register 5 (1035.6199.02).
A9_V_6301 = "1035.6301.02"
A9_V_6199 = "1035.6199.02"
A9_V_UNKNOWN = "UNKNOWN"

# Mapping from the ALCA Varxx string reported by :DIAG:INFO:MOD? to the
# PCB stock number. Populate entries as instruments are sampled.
A9_SCPI_VAR_MAP = {
    "Var04": A9_V_6199,  # observed on SMP02 S/N 848985/012, FW 3.70
}

# Per-variant diagnostic-point ranges. Tuples are (lo, hi, description).
# 6301 values: band-2 p.199 (DE) / p.223 (EN).
# 6199 values: band-2 p.256 (DE) / p.278 (EN).
A9_TP_RANGES = {
    A9_V_6301: {
        "desc": "ALC Amplifier (1035.6301.02)",
        1600: (-0.01, 0.01, "Reference ground"),
        1601: (4.975, 5.025, "Positive reference voltage"),
        1602: (-5.025, -4.975, "Negative reference voltage"),
        1603: (-1.01, 0.00, "AM depth DAC (AM on)"),
        1604: (1.495, 1.505, "AM adder (AM off)"),
        1605: (0.00, 2.5, "FM deviation DACs (FM on)"),
        1606: (0.00, 1.5, "Level DACs (level-dep)"),
        1607: (0.7, 1.1, "Aux. osc. emitter voltage"),
        1608: (-0.005, 0.005, "EXT ALC offset"),
        1609: (0.00, 15.0, "Test amp, mixer iso (jumper X72/X74)"),
        1610: (10.4, 10.8, "Collector V240 (after ALC AMP cal)"),
        1611: (10.4, 10.8, "Collector V250 (after ALC AMP cal)"),
        1612: (-12, 12, "Diff. amp. offset"),
        1613: (-5.0, 0.7, "Main loop control voltage"),
        1614: (-5.0, 0.0, "Limit DAC"),
        1615: (0.00, 0.42, "LF generator"),
    },
    A9_V_6199: {
        "desc": "ALC Amplifier (1035.6199.02)",
        1600: (-0.01, 0.01, "Reference ground"),
        1601: (4.975, 5.025, "Positive reference voltage"),
        1602: (-5.025, -4.975, "Negative reference voltage"),
        1603: (-1.01, 0.00, "AM depth DAC (AM on)"),
        1604: (0.995, 1.005, "AM adder (AM off)"),
        1605: (0.00, 2.5, "FM deviation DACs (FM on)"),
        1606: (0.00, 0.20, "AM modulator IF port (AM off, ~0.1V)"),
        1607: (0.7, 1.6, "Aux. osc. emitter voltage"),
        1608: (-0.005, 0.005, "EXT ALC offset"),
        1609: (0.00, 0.95, "Log Attenuator control (level-dep)"),
        1610: (-0.05, 2.75, "Ref level x93 (0..2.7V <2GHz, 0V >=2GHz)"),
        1611: (-0.05, 2.75, "Ref level x95 (0V <2GHz, 0..2.7V >=2GHz)"),
        1612: (-12, 12, "Diff. amp. offset"),
        1613: (-5.0, 0.7, "Main loop control voltage"),
        1614: (-5.0, 0.0, "Limit DAC"),
        1615: (0.00, 0.42, "LF generator"),
    },
}


def detect_a9_variant_scpi(dev):
    """Detect A9 variant via :DIAG:INFO:MOD?.

    Returns (stock, var, rev). stock is None when the VARxx reported by
    the firmware is not yet in A9_SCPI_VAR_MAP.
    """
    hw = query_hw_modules(dev)
    alca = hw.get("ALCA")
    if alca is None:
        return None, None, None
    var, rev = alca
    return A9_SCPI_VAR_MAP.get(var), var, rev


def detect_a9_variant_tp(dev):
    """Detect A9 variant via TP1604 (AM adder, AM off).

    6301: +1.495..+1.505 V ; 6199: +0.995..+1.005 V. The two windows
    are 500 mV apart and both are frequency- and calibration-independent.
    Returns (stock, v1604).
    """
    dev.write("*RST")
    time.sleep(0.5)
    dev.write("SOUR:AM:STAT OFF")
    dev.write("OUTP:STAT OFF")
    time.sleep(0.3)
    v = read_tp(dev, 1604)
    if 1.35 <= v <= 1.65:
        return A9_V_6301, v
    if 0.85 <= v <= 1.15:
        return A9_V_6199, v
    return A9_V_UNKNOWN, v


def detect_a9_variant(dev, verbose=False):
    """Detect A9 variant using SCPI and TP1604, cross-checking the two.

    Returns the stock number string, or A9_V_UNKNOWN if neither source
    yields a definite answer. When both sources disagree, the physical
    measurement wins and a warning is printed if verbose.
    """
    scpi_stock, var, rev = detect_a9_variant_scpi(dev)
    tp_stock, v1604 = detect_a9_variant_tp(dev)

    if verbose:
        print("A9 variant detection:")
        if var is not None:
            mapped = scpi_stock if scpi_stock else "unmapped VAR"
            print(f"  SCPI   ALCA {var} {rev}   -> {mapped}")
        else:
            print("  SCPI   no ALCA entry in :DIAG:INFO:MOD?")
        print(f"  TP1604 (AM off) {v1604:+.3f} V   -> {tp_stock}")

    if scpi_stock and tp_stock != A9_V_UNKNOWN and scpi_stock != tp_stock:
        if verbose:
            print(
                f"  WARNING: SCPI says {scpi_stock} but TP1604 says {tp_stock};"
                f" trusting TP1604"
            )
        return tp_stock
    if scpi_stock:
        return scpi_stock
    return tp_stock


def read_tp_values(dev, tp):
    """Read a diagnostic test point multiple times, return (values, average).

    Reads READS_PER_POINT samples with READ_DELAY spacing, preceded by
    POINT_DELAY settling time. Returns tuple (values_list, average_value).
    Useful for callers that need both individual samples and the average.
    """
    time.sleep(POINT_DELAY)
    values = []
    for i in range(READS_PER_POINT):
        if i > 0:
            time.sleep(READ_DELAY)
        reply = dev.query(f":DIAG:MEAS:POINT{tp}?")
        values.append(float(reply))
    avg = sum(values) / len(values)
    return values, avg


def check_errors(dev, context=""):
    """Drain error queue and print any errors. Returns True if clean.

    Useful helper that combines drain_err_queue() with error reporting.
    Prints "ERROR [context]: <error>" for each entry; returns False if
    any errors were found.
    """
    errors = drain_err_queue(dev)
    if errors:
        tag = f" [{context}]" if context else ""
        for e in errors:
            print(f"  ERROR{tag}: {e}")
        return False
    return True
